name: CI/CD Pipeline

on:
  push:
    branches:
      - prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build --file recorder.Dockerfile \
            --build-arg FTP_HOST="${{ secrets.FTP_HOST }}" \
            --build-arg FTP_USER="${{ secrets.FTP_USER }}" \
            -t johnny/pi-recorder .

      - name: Push to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_PW }}
          docker push johnny/pi-recorder:latest

      - name: Transfer FTP password
        run: |
          echo ${{ secrets.FTP_PASSWORD }} > ftp.txt
          scp ftp.txt ${{ secrets.PI_SSH_USER }}@${{ secrets.PI_SSH_HOST }}:/home/key/ftp.txt

      - name: Pull and run Docker image on Raspberry Pi
        run: |
          ssh ${{ secrets.PI_SSH_USER }}@${{ secrets.PI_SSH_HOST }} \
            "docker stop pi-recorder || true && docker pull johnny/pi-recorder:latest \
            && docker run -d -e FTP_PASSWORD=$(cat /home/key/ftp.txt) johnny/pi-recorder:latest"
