name: CI/CD Pipeline

on:
  push:
    branches:
      - prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image

        run: |
          docker build --file recorder.Dockerfile \
            --build-arg FTP_HOSTE="${{ secrets.FTP_HOST }}" \
            --build-arg FTP_USER="${{ secrets.FTP_USER }}" \
            --build-arg FTP_PASSWORD="${{ secrets.FTP_PASSWORD }}" \
            -t johnny/recorder .

      - name: Deploy to Raspberry Pi (optional)
        uses: appleboy/scp-action@v0.1.7 # Action for secure file transfer (optional)
        with:
          host: ${{ secrets.PI_SSH_HOST }} # SSH hostname of your Raspberry Pi
          username: ${{ secrets.PI_SSH_USERNAME }}
          password: ${{ secrets.PI_SSH_PASSWORD }}
          source: "docker-compose.yml" # Optional configuration file (explained next)
          target: /home/pi # Target directory on your Raspberry Pi
